# Generated by Django 5.2.7 on 2026-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_seed_datos_reales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='tutor_legal',
            field=models.ManyToManyField(blank=True, related_name='socios', to='socios.tutor'),
        ),
    ]
